# Generated by Django 4.2.4 on 2023-10-24 17:53

from django.db import migrations

def set_price(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    for phone in smartphone_model.objects.all():
        phone.price = len(phone.brand) * 120
        phone.save()
    # smartphone_model.objects.bulk_update(smartphone_model.objects.all(), ['price'])

def set_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    for phone in smartphone_model.objects.all():
        if phone.price >= 750:
            phone.category = 'Expensive'
        else:
            phone.category = "Cheap"
        phone.save()
    # smartphone_model.objects.bulk_update(smartphone_model.objects.all(), ['category'])

def set_price_and_category(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)

def reverse_price_and_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    price_default = smartphone_model._meta.get_field('price').default
    category_default = smartphone_model._meta.get_field('category').default

    for phone in smartphone_model.objects.all():
        phone.category = category_default
        phone.price = price_default
        phone.save()

    # smartphone_model.objects.bulk_update(smartphone_model.objects.all(), ['category', 'price'])

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price_and_category, reverse_code=reverse_price_and_category)
    ]
