# Generated by Django 4.2.4 on 2023-11-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_studentenrollment_alter_student_subjects'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentenrollment',
            table=None,
        ),
    ]
