# Generated by Django 4.2.4 on 2023-11-12 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_restaurant_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0, message='Rating must be at least 0.00.'), django.core.validators.MaxValueValidator(5, message='Rating cannot exceed 5.00.')]),
        ),
    ]
